

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Students_CRUD.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class StudentContext : DbContext
{
    public StudentContext()
        : base("name=StudentContext")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Student> Student { get; set; }

    public virtual DbSet<Notes> Notes { get; set; }

    public virtual DbSet<Subject> Subject { get; set; }

    public virtual DbSet<Teacher> Teacher { get; set; }

    public virtual DbSet<Teacher_Subject> Teacher_Subject { get; set; }

}

}

