
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Students_CRUD.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Notes
{
    [Required]
    public int id_student { get; set; }

    [Required]
    public int id_subject { get; set; }
        [Required]
        public Nullable<int> exam1 { get; set; }
        [Required]
        public Nullable<int> homework { get; set; }
        [Required]
        public Nullable<int> exam2 { get; set; }
        [Required]
        public Nullable<double> avg { get; set; }



    public virtual Student Student { get; set; }

    public virtual Subject Subject { get; set; }

}

}
