//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Students_CRUD.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Notes = new HashSet<Notes>();
        }

        public int id { get; set; }
        [DisplayName("Nombre")]
        [Required]
        public string name { get; set; }
        [DisplayName("Apellido")]
        [Required]
        public string last_name { get; set; }
        [DisplayName("Edad")]
        [Required]
        public Nullable<int> age { get; set; }
        [DisplayName("Genero")]
        [Required]
        public string gender { get; set; }
        [DisplayName("Registrado")]
        public System.DateTime registration_date { get; set; }
         [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notes> Notes { get; set; }
    }
}
