
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Students_CRUD.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Student
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Student()
    {

        this.Notes = new HashSet<Notes>();

    }

<<<<<<< HEAD

    public int id { get; set; }
        [DisplayName("Nombre")]
        [Required]
        public string name { get; set; }
        [DisplayName("Apellido")]
        [Required]
        public string last_name { get; set; }
        [DisplayName("Edad")]
        [Required]
        public Nullable<int> age { get; set; }
        [DisplayName("Genero")]
        [Required]
        public string gender { get; set; }
        [DisplayName("Registrado")]
       
=======
        [Required]
        public int id { get; set; }
        [Required]
        public string name { get; set; }
        [Required]
        public string last_name { get; set; }
        [Required]
        public Nullable<int> age { get; set; }
        [Required]
        public string gender { get; set; }
        [Required]
>>>>>>> 40cbb8848b5e549c619cb9f5a310519745663a30
        public System.DateTime registration_date { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Notes> Notes { get; set; }

}

}
