//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Students_CRUD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Student
    {
        public int id { get; set; }
        [Required]
        [Display(Name="Nombre")]
        public string name { get; set; }
        [Display(Name = "Apellido")]
        public string last_name { get; set; }
        [Display(Name = "Edad")]
        public Nullable<int> age { get; set; }
        [Display(Name = "Género")]
        public string gender { get; set; }
        [Display(Name = "Fecha de registro")]
        public System.DateTime registration_date { get; set; }
    }
}
