
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Students_CRUD.Models
{

using System;
    using System.Collections.Generic;
<<<<<<< HEAD
    using System.ComponentModel;
=======
>>>>>>> 40cbb8848b5e549c619cb9f5a310519745663a30
    using System.ComponentModel.DataAnnotations;

    public partial class Subject
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Subject()
    {

        this.Notes = new HashSet<Notes>();

    }

<<<<<<< HEAD

    public int id { get; set; }
        [DisplayName("Nombre")]
=======
        [Required]
        public int id { get; set; }
>>>>>>> 40cbb8848b5e549c619cb9f5a310519745663a30
        [Required]
        public string name { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Notes> Notes { get; set; }

}

}
